ci: Use an emulator cache key that is specific to the PR/branch/tag in all workflows
Fixes instrumented test failures caused by
com.android.ddmlib.InstallException: INSTALL_FAILED_UPDATE_INCOMPATIBLE:
Package net.gini.android.capture.network.test signatures do not match previously
installed version; ignoring!

These happened when there was more than one PR using the `avd-x86_64-31` cache key.